#! /bin/bash

./extra_tools/resetfiles

echo "Extracting 'air-quality-data-2004-2019.csv' into multiple CSVs"
php task1/extract-to-csv.php

echo "Normalising the split CSVs into multiple XML documents"
php task2/normalize-to-xml.php

echo "Count the lines in each document"
php extra_tools/count_lines.php

echo "Validate each XML document against the XSD Schema"
php extra_tools/validate_xml_xsd.php